# Modulpfad
ZSH_MODULES_DIR=~/.zsh/modules

# Default Texteditor
export EDITOR="nvim"
export VISUAL="nvim"

# Module laden (Farben zuerst)
source ~/.zsh/modules/colors.zsh

# Lade alle anderen Module
for module in ~/.zsh/modules/*.zsh; do
    [[ "$module" == *colors.zsh ]] && continue
    source "$module"
done

